### ISSUE TITLE
Exception Unhandled

### ISSUE THREAD

**Issue by Pusher91** [rasta-mouse/Watson#21]
I'm running into the below error and I'm not sure why.  This is freshly downloaded.  Watson worked for me before, I reinstalled/reformatted Windows, and now it will not run.

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Watson.Program.Main(String[] args) in C:\Users\\****\Source\Repos\Watson\Watson\Program.cs:line 25

Thanks

**Comment by Pusher91** [comment]
I was running this on a version of Windows that is unsupported.
