### ISSUE TITLE
keyNotFoundException issue

### ISSUE THREAD

**Issue by infosecx0** [rasta-mouse/Watson#22]
```
C:\Users\dadp0\Desktop\AV Evasion projects\Watson-master\Watson\bin\Debug>Watson.exe
  __    __      _
 / / /\ \ \__ _| |_ ___  ___  _ __
 \ \/  \/ / _` | __/ __|/ _ \| '_ \
  \  /\  / (_| | |_\__ \ (_) | | | |
   \/  \/ \__,_|\__|___/\___/|_| |_|

                           v2.0

                   @_RastaMouse


Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Watson.Program.Main(String[] args) in C:\Users\dadp0\Desktop\AV Evasion projects\Watson-master\Watson\Program.cs:line 25
```

**Comment by dvs17** [comment]
> 
> 
> :\Users\dadp0\Desktop\AV Evasion projects\Watson-master\Watson\bin\Debug>Watson.exe
> 
> / / /\ \ __ _| |_ ___ ___ _ __
> \ / / / _` | __/ __|/ _ | '_ \ /\ / (_| | |___ \ (_) | | | | / / __,_|__|_**/_**/|_| |_|
> 
> ```
>                        v2.0
> 
>                @_RastaMouse
> ```
> 
> Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
> at System.ThrowHelper.ThrowKeyNotFoundException()
> at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> at Watson.Program.Main(String[] args) in C:\Users\dadp0\Desktop\AV Evasion projects\Watson-master\Watson\Program.cs:line 25

Had the same issue, fixed by adding { 19042, "20H2" } to the list of supported versions.

**Comment by rasta-mouse** [comment]
Yeah, but none of the vulnerability definitions has entries for 19042 / 20H2, so it will always report no vulnerabilities found.
The actual solution is to throw an OperatingSystemNotSupported Exception or just print a message to the console and return.

**Comment by rasta-mouse** [comment]
Didn't mean to close...

**Comment by von-der-eretier** [comment]
I'm having this issue on a Microsoft Windows 7 Enterprise 6.1.7600 N/A Build 7600 x86, compiled watson por x86bits but nothing. 
Any solutions?

**Comment by rasta-mouse** [comment]
The "solution" is to stop running the tool on versions of Windows that the README doesn't say are supported...

**Comment by von-der-eretier** [comment]
ups sorry, you can delete my post x)

**Comment by Kinny092** [comment]
Thanks, please keep this up. I had the exact same issue. its useful, if i have not seen this, I would post this issue again.
